---@type vim.lsp.Config
return {
    filetypes = { "markdown" },
    init_options = {
        autoInstall = true,
        languageServers = {
            astro = {
                cmd = { "astro-ls", "--stdio" },
                languages = { "astro" },
            },
            bashls = {
                cmd = { "bash-language-server", "start" },
                languages = { "bash", "sh" },
            },
            biome = {
                cmd = { "biome", "lsp-proxy" },
                languages = {
                    "astro",
                    "css",
                    "graphql",
                    "html",
                    "javascript",
                    "javascriptreact",
                    "json",
                    "jsonc",
                    "svelte",
                    "typescript",
                    "typescriptreact",
                    "vue",
                },
            },
            cssls = {
                cmd = { "vscode-css-language-server", "--stdio" },
                languages = { "css", "scss", "less" },
            },
            denols = {
                cmd = { "deno", "lsp" },
                languages = { "javascript", "javascriptreact", "typescript", "typescriptreact" },
            },
            eslint = {
                cmd = { "vscode-eslint-language-server", "--stdio" },
                languages = {
                    "javascript",
                    "javascriptreact",
                    "typescript",
                    "typescriptreact",
                    "vue",
                    "svelte",
                    "astro",
                    "htmlangular",
                },
            },
            gleam = {
                cmd = { "gleam", "lsp" },
                languages = { "gleam" },
            },
            gopls = {
                cmd = { "gopls" },
                languages = { "go", "gomod", "gowork", "gotmpl" },
            },
            html = {
                cmd = { "vscode-html-language-server", "--stdio" },
                languages = { "html" },
            },
            jsonls = {
                cmd = { "vscode-json-language-server", "--stdio" },
                languages = { "json", "jsonc" },
            },
            lua_ls = {
                cmd = { "lua-language-server" },
                languages = { "lua" },
            },
            nixd = {
                cmd = { "nixd" },
                languages = { "nix" },
            },
            oxfmt = {
                cmd = { "oxfmt", "--lsp" },
                languages = {
                    "javascript",
                    "javascriptreact",
                    "typescript",
                    "typescriptreact",
                    "toml",
                    "json",
                    "jsonc",
                    "json5",
                    "yaml",
                    "html",
                    "vue",
                    "handlebars",
                    "css",
                    "scss",
                    "less",
                    "graphql",
                    "markdown",
                },
            },
            oxlint = {
                cmd = { "oxlint", "--lsp" },
                languages = {
                    "javascript",
                    "javascriptreact",
                    "typescript",
                    "typescriptreact",
                    "vue",
                    "svelte",
                    "astro",
                },
            },
            pylsp = {
                cmd = { "pylsp" },
                languages = { "python" },
            },
            rust_analyzer = {
                cmd = { "rust-analyzer" },
                languages = { "rust" },
            },
            tailwindcss = {
                cmd = { "tailwindcss-language-server", "--stdio" },
                languages = {
                    "aspnetcorerazor",
                    "astro",
                    "astro-markdown",
                    "blade",
                    "clojure",
                    "django-html",
                    "htmldjango",
                    "edge",
                    "eelixir",
                    "elixir",
                    "ejs",
                    "erb",
                    "eruby",
                    "gohtml",
                    "gohtmltmpl",
                    "haml",
                    "handlebars",
                    "hbs",
                    "html",
                    "htmlangular",
                    "html-eex",
                    "heex",
                    "jade",
                    "leaf",
                    "liquid",
                    "markdown",
                    "mdx",
                    "mustache",
                    "njk",
                    "nunjucks",
                    "php",
                    "razor",
                    "slim",
                    "twig",
                    "css",
                    "less",
                    "postcss",
                    "sass",
                    "scss",
                    "stylus",
                    "sugarss",
                    "javascript",
                    "javascriptreact",
                    "reason",
                    "rescript",
                    "typescript",
                    "typescriptreact",
                    "vue",
                    "svelte",
                    "templ",
                },
            },
            tsp_server = {
                cmd = { "tsp-server", "--stdio" },
                languages = { "typespec" },
            },
            version_lsp = {
                cmd = { "version-lsp" },
                languages = { "json", "jsonc", "toml", "gomod", "yaml" },
            },
            vtsls = {
                cmd = { "vtsls", "--stdio" },
                languages = { "javascript", "javascriptreact", "typescript", "typescriptreact" },
            },
        },
    },
    on_attach = function(_, bufnr)
        -- Avoid double highlighting with tree-sitter-manager.nvim's auto-started highlighter
        vim.api.nvim_create_autocmd("LspTokenUpdate", {
            buffer = bufnr,
            once = true,
            callback = function()
                vim.treesitter.stop(bufnr)
            end,
        })
    end,
}
