return {
    {
        "nvim-treesitter/nvim-treesitter",
        branch = "main",
        dependencies = { "nvim-treesitter/nvim-treesitter-context" },
        lazy = false,
        build = ":TSUpdate",
        config = function()
            require("nvim-treesitter").setup {}
            require("nvim-treesitter").install {
                "astro",
                "bash",
                "c",
                "c_sharp",
                "cpp",
                "css",
                "csv",
                "dart",
                "diff",
                "dockerfile",
                "git_config",
                "git_rebase",
                "gitcommit",
                "gitignore",
                "gleam",
                "go",
                "graphql",
                "html",
                "ini",
                "java",
                "javascript",
                "jsdoc",
                "json",
                "json5",
                "jsonc",
                "kdl",
                "kotlin",
                "lua",
                "luadoc",
                "luap",
                "markdown",
                "markdown_inline",
                "nix",
                "php",
                "prisma",
                "python",
                "query",
                "r",
                "regex",
                "rust",
                "scss",
                "sql",
                "toml",
                "tsx",
                "typescript",
                "vim",
                "vimdoc",
                "vue",
                "xml",
                "yaml",
            }
            require("treesitter-context").setup {
                enable = true,
                max_lines = 5,
                min_window_height = 0,
                line_numbers = true,
                multiline_threshold = 20,
                trim_scope = "outer",
                mode = "cursor",
                separator = nil,
                zindex = 20,
                on_attach = nil,
            }
            vim.api.nvim_create_autocmd("FileType", {
                group = vim.api.nvim_create_augroup("vim-treesitter-start", {}),
                callback = function()
                    pcall(vim.treesitter.start)
                end,
            })
        end,
    },
}
